version: '3'

volumes:
  local_demo_postgres_data: {}
  local_demo_postgres_data_backups: {}

services:
  django: &django
    build:
      context: ../../
      dockerfile: ./docker/local/django/Dockerfile
    image: django_channels_demo_local_django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - ./../..:/app
    env_file:
      - ../../.envs/.local/.django
      - ../../.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  django_vscode:
    <<: *django
    container_name: django_channels_demo_vscode_local_django
    command: sleep infinity

  redis:
    image: redis:3.2

  postgres:
    build:
      context: ../../
      dockerfile: ./docker/production/postgres/Dockerfile
    image: django_channels_demo_production_postgres
    volumes:
      - local_demo_postgres_data:/var/lib/postgresql/data
      - local_demo_postgres_data_backups:/backups
    env_file:
      - ../../.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"
